name: Build Linux AppImage (NanoPrint)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk tk tcl curl

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build GUI binary
        run: |
          pyinstaller --windowed --name NanoPrint nanoprint.py

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin AppDir/usr/share/icons/hicolor/256x256/apps
          cp dist/NanoPrint AppDir/usr/bin/
          cat > AppDir/NanoPrint.desktop << 'EOF'
          [Desktop Entry]
          Type=Application
          Name=NanoPrint
          Exec=NanoPrint
          Icon=nanoprint
          Categories=Graphics;
          EOF
          python - << 'PY'
          from PIL import Image, ImageDraw
          img = Image.new('RGBA', (256,256), (18,18,18,255))
          d = ImageDraw.Draw(img)
          d.rectangle([16,16,240,240], outline=(255,255,255,255), width=6)
          d.text((40,100), 'NP', fill=(255,255,255,255))
          img.save('AppDir/usr/share/icons/hicolor/256x256/apps/nanoprint.png')
          PY

      - name: Build AppImage
        run: |
          curl -L -o linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy
          ./linuxdeploy --appdir AppDir --desktop-file AppDir/NanoPrint.desktop \
            --executable AppDir/usr/bin/NanoPrint \
            --icon-file AppDir/usr/share/icons/hicolor/256x256/apps/nanoprint.png \
            --output appimage
          mv *.AppImage NanoPrint-x86_64.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NanoPrint-linux-appimage
          path: NanoPrint-x86_64.AppImage
