name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build Windows EXE
        run: |
          pyinstaller --windowed --onefile --name NanoPrint \
            --collect-all numpy --collect-all shapely --collect-all PIL --collect-all pymupdf \
            nanoprint.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: NanoPrint-windows
          path: |
            dist/NanoPrint.exe
          if-no-files-found: error

